apiVersion: v1
kind: Service
metadata:
  name: active-mq-node-port # Sets service name
  labels:
    app: active-mq-node-port # Labels and Selectors
spec:
  type: NodePort # Sets service type
  ports:
    - port: 61613 # Sets port to run the postgres application
      targetPort: 61613
      nodePort: 31613
  selector:
    app: active-mq